language: ruby
sudo: true
cache: bundler
rvm:
- 2.1.6
services:
- redis-server
addons:
  apt:
    packages:
    - aspell
    - aspell-en
    - libaspell-dev
before_install:
- wget https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.4.4.deb
- sudo dpkg -i elasticsearch-1.4.4.deb
- sudo update-rc.d elasticsearch defaults 95 10
- 'echo "script.disable_dynamic: false" | sudo tee -a /etc/elasticsearch/elasticsearch.yml'
- sudo /etc/init.d/elasticsearch start
- sleep 10
env:
  global:
  - GOVUK_APP_DOMAIN: dev
  - DEV_DOMAIN: dev
  - STATIC_DEV: http://static.dev
  - GOVUK_ASSET_ROOT: static.dev
  - PANOPTICON_USER: api
  - PANOPTICON_PASSWORD: mysuperawesomepassword
  - CONTENTAPI_DEFAULT_ROLE: odi
  - RUMMAGER_HOST: http://search.dev
  - QUIRKAFLEEG_ELASTICSEARCH_LOCATION: http://localhost:9200
