language: ruby
sudo: true
cache: bundler
rvm:
- 2.1.6
deploy:
  provider: heroku
  strategy: api
  app: odi-rummager
  on:
    repo: theodi/rummager
  api_key:
    secure: jbPeh9KiLPN/Qfw43SggdFLoaCkKAKWIWDR8AkJkgX7heH9kuIuD1fHQGuiuk3a6/p6zMIcnKrcxdZiR5fwcXvfNs+SDzm3HMVut79oAgGFYgmu0G0SpV8hv3e8g+6QzWZLzGMDj6wDTAwynGR9wdyibOf0qqSjqde0PVyUDlHY=
services:
- redis-server
addons:
  apt:
    packages:
    - aspell
    - aspell-en
    - libaspell-dev
before_install:
- wget https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.4.4.deb
- sudo dpkg -i elasticsearch-1.4.4.deb
- sudo update-rc.d elasticsearch defaults 95 10
- 'echo "script.disable_dynamic: false" | sudo tee -a /etc/elasticsearch/elasticsearch.yml'
- sudo /etc/init.d/elasticsearch start
- sleep 10
branches:
  except:
  - CURRENT
notifications:
  irc:
    channels:
    - irc.freenode.net#theodi
    template:
    - "%{repository} %{branch} - %{message} %{build_url}"
    on_success: change
    on_failure: always
env:
  global:
  - GOVUK_APP_DOMAIN: dev
  - DEV_DOMAIN: dev
  - STATIC_DEV: http://static.dev
  - GOVUK_ASSET_ROOT: static.dev
  - PANOPTICON_USER: api
  - PANOPTICON_PASSWORD: mysuperawesomepassword
  - CONTENTAPI_DEFAULT_ROLE: odi
  - RUMMAGER_HOST: http://search.dev
  - QUIRKAFLEEG_ELASTICSEARCH_LOCATION: http://localhost:9200
  - secure: Tf0wil4Gx4e00gV2G300h8UfKnBC+D3BextrYiGNHXaydjNsl6fBh85MVa3hfISJHEuE+uKYWwiJpMqRudibLfbssAn/YysymY5vayOdr8ayJUdjmJAkzZt8GJrOM1IG2E6BAeCFETDGnRH1d3We3GnikqdpP7u16/7saYJULPc=
  - secure: R5LsgTYEsweOSqArgVpYYJ35yzT2Enon6SXAM8QfxqFci8hjB3sDabT+Jf5ca/mfDmzl5YEBmedYzdLhyZd5ifNmO//n7LsrZ2KmE0uUiFufvRH02eDlOYfoOOUqFv2HZdEquD1i0w53854mz0CUZK+TJbF427ojmQTLn3NqGxI=
