language: ruby
sudo: true
cache: bundler
rvm:
- 2.1.6
after_success:
- ! '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] &&
  curl -v -X DELETE -u $GITHUB_USER:$GITHUB_PASSWORD "https://api.github.com/repos/$TRAVIS_REPO_SLUG/git/refs/tags/CURRENT"'
- ! '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] &&
  curl -v -X POST -d ''{"ref":"refs/tags/CURRENT","sha":"''$TRAVIS_COMMIT''"}''  --header
  "Content-Type:application/json" -u $GITHUB_USER:$GITHUB_PASSWORD "https://api.github.com/repos/$TRAVIS_REPO_SLUG/git/refs"'
services:
- redis-server
addons:
  apt:
    packages:
    - aspell
    - aspell-en
    - libaspell-dev
before_install:
  - wget https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.4.4.deb
  - sudo dpkg -i elasticsearch-1.4.4.deb
  - sudo update-rc.d elasticsearch defaults 95 10
  - 'echo "script.disable_dynamic: false" | sudo tee -a /etc/elasticsearch/elasticsearch.yml'
  - sudo /etc/init.d/elasticsearch start
  - sleep 10
branches:
  except:
  - CURRENT
notifications:
  irc:
    channels:
    - irc.freenode.net#theodi
    template:
    - ! '%{repository} %{branch} - %{message} %{build_url}'
    on_success: change
    on_failure: always
env:
  global:
  - GOVUK_APP_DOMAIN: dev
  - DEV_DOMAIN: dev
  - STATIC_DEV: http://static.dev
  - GOVUK_ASSET_ROOT: static.dev
  - PANOPTICON_USER: api
  - PANOPTICON_PASSWORD: mysuperawesomepassword
  - CONTENTAPI_DEFAULT_ROLE: odi
  - RUMMAGER_HOST: http://search.dev
  - secure: Tf0wil4Gx4e00gV2G300h8UfKnBC+D3BextrYiGNHXaydjNsl6fBh85MVa3hfISJHEuE+uKYWwiJpMqRudibLfbssAn/YysymY5vayOdr8ayJUdjmJAkzZt8GJrOM1IG2E6BAeCFETDGnRH1d3We3GnikqdpP7u16/7saYJULPc=
  - secure: R5LsgTYEsweOSqArgVpYYJ35yzT2Enon6SXAM8QfxqFci8hjB3sDabT+Jf5ca/mfDmzl5YEBmedYzdLhyZd5ifNmO//n7LsrZ2KmE0uUiFufvRH02eDlOYfoOOUqFv2HZdEquD1i0w53854mz0CUZK+TJbF427ojmQTLn3NqGxI=
